In [3]:
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
from geopy.geocoders import Nominatim
import folium
import requests

In [4]:
url="https://www.mapsofindia.com/pincode/india/maharashtra/mumbai/"
request=requests.get(url).text
type(request)

page=BeautifulSoup(request,'lxml')


In [5]:
div=page.find('div',class_='tables table2 sliderespone')
table=page.find('table')

In [6]:
columns = []
for column in table.find_all('th'):
    columns.append(column.text.replace('\n',''))
    
columns

['Pincode Details']

In [7]:
all = []
for tr in table.find_all('tr'):    
    row=[]
    for col in tr.find_all('td'):
        row.append(col.text.replace('\n',''))    
    all.append(row)

In [8]:
df = pd.DataFrame(all, columns=['Area', 'Pincode', 'State', 'District'])
df.drop(0, inplace=True) #dropping 0th index row. for some reason it was adding a None Value row
df.drop(1, inplace=True)
df.sort_values('Pincode').head()


Area  Pincode        State District
94           M.P.t.  400001   Maharashtra  Mumbai 
19        Bazargate  400001   Maharashtra  Mumbai 
119         Mumbai.  400001   Maharashtra  Mumbai 
160  Stock Exchange  400001   Maharashtra  Mumbai 
161        Tajmahal  400001   Maharashtra  Mumbai

In [9]:
df=df.reset_index(drop=True)
df=df.drop(['State'],axis=1)
df.head()

Area  Pincode District
0  A I staff colony  400029   Mumbai 
1  Aareymilk Colony  400065   Mumbai 
2          Agripada  400011   Mumbai 
3           Airport  400099   Mumbai 
4          Ambewadi  400004   Mumbai

In [10]:
[pincode for pincode in df['Pincode']]

['400029 ',
 '400065 ',
 '400011 ',
 '400099 ',
 '400004 ',
 '400053 ',
 '400069 ',
 '400058 ',
 '400037 ',
 '400005 ',
 '400053 ',
 '400003 ',
 '400051 ',
 '400003 ',
 '400050 ',
 '400051 ',
 '400090 ',
 '400001 ',
 '400012 ',
 '400007 ',
 '400028 ',
 '400028 ',
 '400091 ',
 '400066 ',
 '400092 ',
 '400013 ',
 '400020 ',
 '400030 ',
 '400093 ',
 '400012 ',
 '400067 ',
 '400004 ',
 '400004 ',
 '400009 ',
 '400011 ',
 '400020 ',
 '400005 ',
 '400033 ',
 '400026 ',
 '400026 ',
 '400014 ',
 '400014 ',
 '400068 ',
 '400068 ',
 '400052 ',
 '400066 ',
 '400013 ',
 '400017 ',
 '400017 ',
 '400010 ',
 '400026 ',
 '400008 ',
 '400004 ',
 '400028 ',
 '400062 ',
 '400063 ',
 '400062 ',
 '400051 ',
 '400026 ',
 '400007 ',
 '400058 ',
 '400012 ',
 '400011 ',
 '400034 ',
 '400057 ',
 '400032 ',
 '400005 ',
 '400056 ',
 '400095 ',
 '400099 ',
 '400059 ',
 '400008 ',
 '400011 ',
 '400060 ',
 '400102 ',
 '400049 ',
 '400033 ',
 '400002 ',
 '400008 ',
 '400101 ',
 '400067 ',
 '400016 ',
 '400068 ',
 '40

In [11]:
url = 'https://www.whatsuplife.in/delhi/blog/zip-pin-postal-code-pincodes-delhi/'
request=requests.get(url).text

page=BeautifulSoup(request,'lxml')

In [12]:
div = page.find('div', class_ = 'post-content description ')

In [13]:
district = []
for span in div.find_all('span'):
    district.append(span.text.replace('\xa0',' '))

In [14]:
district = district[:7]
district

['CENTRAL DELHI',
 'SOUTH DELHI',
 'WEST DELHI',
 'NORTH DELHI',
 'EAST DELHI',
 'SOUTH WEST DELHI',
 'NORTH WEST DELHI']

In [15]:
all_d = []
for d in district:
    url_d = ('https://www.mapsofindia.com/pincode/india/delhi/{}/').format(d.replace(' ','-'))
    print(url_d)
    request_d = requests.get(url_d).text
    page_d = BeautifulSoup(request_d,'lxml')    
    div_d = page_d.find('div', class_='tables table2 sliderespon')
    table_d = page_d.find('table')
    for tr_d in table_d.find_all('tr'):    
        row_d=[]
        for col_d in tr_d.find_all('td'):
            row_d.append(col_d.text.replace('\n',''))    
        all_d.append(row_d)

https://www.mapsofindia.com/pincode/india/delhi/CENTRAL-DELHI/
https://www.mapsofindia.com/pincode/india/delhi/SOUTH-DELHI/
https://www.mapsofindia.com/pincode/india/delhi/WEST-DELHI/
https://www.mapsofindia.com/pincode/india/delhi/NORTH-DELHI/
https://www.mapsofindia.com/pincode/india/delhi/EAST-DELHI/
https://www.mapsofindia.com/pincode/india/delhi/SOUTH-WEST-DELHI/
https://www.mapsofindia.com/pincode/india/delhi/NORTH-WEST-DELHI/


In [16]:
all_d

[[],
 ['Location', 'Pincode ', 'State ', 'District '],
 ['A.G.c.r.', '110002 ', 'Delhi', 'Central Delhi '],
 ['A.K.market', '110055 ', 'Delhi', 'Central Delhi '],
 ['Ajmeri Gate extn.', '110002 ', 'Delhi', 'Central Delhi '],
 ['Anand Parbat', '110005 ', 'Delhi', 'Central Delhi '],
 ['Anand Parbat indl. area', '110005 ', 'Delhi', 'Central Delhi '],
 ['Bank Street', '110005 ', 'Delhi', 'Central Delhi '],
 ['Baroda House', '110001 ', 'Delhi', 'Central Delhi '],
 ['Bengali Market', '110001 ', 'Delhi', 'Central Delhi '],
 ['Bhagat Singh market', '110001 ', 'Delhi', 'Central Delhi '],
 ['Connaught Place', '110001 ', 'Delhi', 'Central Delhi '],
 ['Constitution House', '110001 ', 'Delhi', 'Central Delhi '],
 ['Dada Ghosh bhawan', '110008 ', 'Delhi', 'Central Delhi '],
 ['Darya Ganj', '110002 ', 'Delhi', 'Central Delhi '],
 ['Delhi High court', '110003 ', 'Delhi', 'Central Delhi '],
 ['Desh Bandhu gupta road', '110005 ', 'Delhi', 'Central Delhi '],
 ['Election Commission', '110001 ', 'Delhi', '

In [17]:
dfd=pd.DataFrame(all_d,columns=['Area','Pincode','State','District'])

In [19]:
dfd = dfd[pd.notnull(dfd['Area'])]
dfd = dfd[dfd['Area'] != 'Location']


In [20]:
dfd.head()

Area  Pincode  State        District
2                 A.G.c.r.  110002   Delhi  Central Delhi 
3               A.K.market  110055   Delhi  Central Delhi 
4        Ajmeri Gate extn.  110002   Delhi  Central Delhi 
5             Anand Parbat  110005   Delhi  Central Delhi 
6  Anand Parbat indl. area  110005   Delhi  Central Delhi

In [21]:
dfd=dfd.reset_index(drop=True)
dfd=dfd.drop(['State'],axis=1)
dfd.head()

Area  Pincode        District
0                 A.G.c.r.  110002   Central Delhi 
1               A.K.market  110055   Central Delhi 
2        Ajmeri Gate extn.  110002   Central Delhi 
3             Anand Parbat  110005   Central Delhi 
4  Anand Parbat indl. area  110005   Central Delhi

In [22]:
def get_latitude_longitude(area):
    address='{},India'.format(area)
    geo_locator=Nominatim(user_agent="get_latlong")
    location=geo_locator.geocode(address,timeout=30)
    if location is None:
        latitude=None
        longitude=None
    else:
        latitude=location.latitude
        longitude=location.longitude
        
    return [latitude,longitude]   

In [23]:
loc=get_latitude_longitude('110018')

In [24]:
loc

[28.6338964119353, 77.0820948893626]

In [30]:
m_latlong=[]
i=0
for area in df['Area']:
    m_latlong.append(get_latitude_longitude(area+',Mumbai'))
    print(i)
    i=i+1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181


In [31]:
d_latlong=[]
i=0
for area in dfd['Area']:
    d_latlong.append(get_latitude_longitude(area+',Delhi'))
    print(i)
    i=i+1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [62]:
df_m_ll=pd.DataFrame(m_latlong,columns=['Latitude','Longitude'])
df_d_ll=pd.DataFrame(d_latlong,columns=['Latitude','Longitude'])

df['Latitude']=df_m_ll['Latitude']
df['Longitude']=df_m_ll['Longitude']

dfd['Latitude']=df_d_ll['Latitude']
dfd['Longitude']=df_d_ll['Longitude']



In [63]:


df = df[np.isfinite(df['Latitude'])]
dfd = dfd[np.isfinite(dfd['Latitude'])]



In [64]:
df.to_csv('mumbai_pincodes.csv')
dfd.to_csv('delhi_pincodes.csv')

In [65]:
df

Area  Pincode District   Latitude  Longitude
2                   Agripada  400011   Mumbai   18.975302  72.824898
3                    Airport  400099   Mumbai   19.090201  72.863808
4                   Ambewadi  400004   Mumbai   19.186776  72.859313
5                    Andheri  400053   Mumbai   19.120371  72.848043
6               Andheri East  400069   Mumbai   19.115883  72.854202
7    Andheri Railway station  400058   Mumbai   19.120371  72.848043
8                 Antop Hill  400037   Mumbai   19.020761  72.865256
9                     Asvini  400005   Mumbai   18.900867  72.815941
10                Azad Nagar  400053   Mumbai   19.165798  72.955893
11              B P t colony  400003   Mumbai   19.101937  72.861599
12               B.N. bhavan  400051   Mumbai   18.937132  72.832556
14               Bandra West  400050   Mumbai   19.058336  72.830267
15              Bandra(east)  400051   Mumbai   19.061657  72.849811
16              Bangur Nagar  400090   Mumbai   19.168814  72.833678
17                 Bazargate  400001   Mumbai   18.928665  72.832264
18         Best Staff colony  400012   Mumbai   19.050611  72.858869
19              Bharat Nagar  400007   Mumbai   19.063330  72.856474
20           Bhawani Shankar  400028   Mumbai   19.015786  72.837370
22                  Borivali  400091   Mumbai   19.228738  72.856877
23             Borivali East  400066   Mumbai   19.226723  72.861933
27              Century Mill  400030   Mumbai   19.008301  72.825146
28              Chakala Midc  400093   Mumbai   19.115287  72.861808
29                Chamarbaug  400012   Mumbai   19.001759  72.840800
30                   Charkop  400067   Mumbai   19.214119  72.825865
31               Charni Road  400004   Mumbai   18.951805  72.818668
33              Chinchbunder  400009   Mumbai   18.956751  72.837053
34               Chinchpokli  400011   Mumbai   18.987198  72.832672
35                Churchgate  400020   Mumbai   18.933927  72.827349
36                    Colaba  400005   Mumbai   18.915091  72.825969
37           Cotton Exchange  400033   Mumbai   18.987249  72.845762
..                       ...      ...      ...        ...        ...
122            Nariman Point  400021   Mumbai   18.925951  72.823208
123      New Prabhadevi road  400025   Mumbai   19.011622  72.828821
124           New Yogakshema  400021   Mumbai   18.929668  72.823355
126               Null Bazar  400003   Mumbai   18.928665  72.832264
127              Opera House  400004   Mumbai   18.956345  72.815505
128                    Orlem  400064   Mumbai   19.194482  72.838966
129                 Oshiwara  400102   Mumbai   19.150244  72.834229
130                    Parel  400012   Mumbai   19.009482  72.837661
131               Parel Naka  400012   Mumbai   19.005325  72.839898
133               Prabhadevi  400025   Mumbai   19.014881  72.827956
136           Rajendra Nagar  400066   Mumbai   19.220945  72.856423
138              Ranade Road  400028   Mumbai   19.022111  72.838969
139           Rani Sati marg  400097   Mumbai   19.183766  72.849538
140                Reay Road  400033   Mumbai   18.977551  72.844101
142          S Savarkar marg  400028   Mumbai   19.014726  72.826480
148        Santacruz Central  400054   Mumbai   19.081522  72.841757
150          Santacruz(east)  400055   Mumbai   19.081522  72.841757
151          Santacruz(west)  400054   Mumbai   19.084877  72.834973
153                    Seepz  400096   Mumbai   19.125356  72.875170
154                    Sewri  400015   Mumbai   18.998780  72.854422
156             Shivaji Park  400028   Mumbai   19.028745  72.839161
158           Stock Exchange  400001   Mumbai   18.929832  72.833361
160                Tank Road  400033   Mumbai   19.028166  72.868325
161                   Tardeo  400007   Mumbai   18.967275  72.822151
163                Town Hall  400001   Mumbai   18.938771  72.835335
164                Tulsiwadi  400034   Mumbai   18.973459  72.818097
169                   

In [66]:
dfd


Area  Pincode           District   Latitude  Longitude
5               Bank Street  110005      Central Delhi   28.651718  77.221939
6              Baroda House  110001      Central Delhi   28.615804  77.230020
7            Bengali Market  110001      Central Delhi   28.629465  77.232185
9           Connaught Place  110001      Central Delhi   28.631383  77.219792
13         Delhi High court  110003      Central Delhi   28.608764  77.236435
14   Desh Bandhu gupta road  110005      Central Delhi   28.645182  77.223261
15      Election Commission  110001      Central Delhi   28.448733  77.028976
17   Guru Gobind singh marg  110005      Central Delhi   28.533065  77.208283
20                 I.A.r.i.  110012      Central Delhi   28.648948  77.183660
22                Inderpuri  110012      Central Delhi   28.628684  77.147098
23             Indraprastha  110002      Central Delhi   28.620583  77.249545
24              Jama Masjid  110006      Central Delhi   28.650045  77.237686
25                  Janpath  110001      Central Delhi   28.610086  77.218247
26               Karol Bagh  110005      Central Delhi   28.652998  77.189023
27            Krishi Bhawan  110001      Central Delhi   28.616831  77.213691
30               Minto Road  110002      Central Delhi   28.639178  77.224313
31           Multani Dhanda  110055      Central Delhi   28.647279  77.210627
33            Nirman Bhawan  110011      Central Delhi   28.611132  77.214613
34             North Avenue  110001      Central Delhi   28.623590  77.199990
35               Pahar Ganj  110055      Central Delhi   28.639852  77.213031
36             Pandara Road  110003      Central Delhi   28.602844  77.230751
37         Parliament House  110001      Central Delhi   28.617188  77.207808
38              Patel Nagar  110008      Central Delhi   28.659809  77.156957
39         Patel Nagar east  110008      Central Delhi   28.645035  77.169302
40        Patel Nagar south  110008      Central Delhi   28.659809  77.156957
41         Patel Nagar west  110008      Central Delhi   28.659809  77.156957
42            Patiala House  110001      Central Delhi   28.616533  77.233753
43           Pragati Maidan  110001      Central Delhi   28.623459  77.242512
44              Rail Bhawan  110001      Central Delhi   28.614939  77.211989
46      Rajghat Power house  110002      Central Delhi   28.637893  77.254847
..                      ...      ...                ...        ...        ...
479          Model Town iii  110009   North West delhi   28.702739  77.194006
481              Mukhmelpur  110036   North West delhi   28.792134  77.162158
482               N.S.mandi  110033   North West delhi   28.439753  77.143405
485                  Narela  110040   North West delhi   28.842610  77.091835
487               Naya Bans  110082   North West delhi   28.785477  77.093965
488                   Nimri  110052   North West delhi   28.681127  77.174137
489        Nirankari Colony  110009   North West delhi   28.716571  77.206419
490                Nizampur  110081   North West delhi   28.717640  76.959769
491             Onkar Nagar  110035   North West delhi   28.674341  77.160629
492                   Palla  110036   North West delhi   28.842895  77.185547
497             Power House  110035   North West delhi   28.651718  77.221939
498          Prashant Vihar  110085   North West delhi   28.714448  77.138999
499             Punjab Khor  110081   North West delhi   28.775589  76.963019
501                 Rampura  110035   North West delhi   28.676074  77.155086
502               Rani Bagh  110034   North West delhi   28.685982  77.132524
503              Rani Khera  110081   North West delhi   28.706176  77.023419
504                 Rithala  110085   North West delhi   28.720806  77.107181
506        Rohini Sector 15  110089   North West delhi   28.716209  77.117074
507         Rohini Sector 5  110085   North West delhi   28.716209  77.117074
508         Rohini Sector-7  110085   North W

In [67]:
from geopy.geocoders import Nominatim
import folium
address='Mumbai,India'
geolocator=Nominatim(user_agent="get_latlong")
location=geolocator.geocode(address,timeout=10)
latitude=location.latitude
longitude=location.longitude

map_mumbai=folium.Map(location=[latitude,longitude],zoom_start=10)

for lat, lng, borough, neighborhood in zip(df['Latitude'], df['Longitude'], df['District'], df['Area']):
    label = '{}, {}'.format(neighborhood, borough)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_mumbai)  
    
    map_mumbai

In [82]:
from geopy.geocoders import Nominatim
import folium

address='Delhi,India'
geolocator=Nominatim(user_agent='get_lat_long')
location=geolocator.geocode(address,timeout=10)
latitude=location.latitude
longitude=location.longitude

map_delhi=folium.Map(location=[latitude,longitude],zoom_start=10)

for lat, lng, borough, neighborhood in zip(dfd['Latitude'], dfd['Longitude'], dfd['District'], dfd['Area']):
    label = '{}, {}'.format(neighborhood, borough)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_delhi)  
    
    map_delhi


In [83]:
df.groupby('Pincode').count().sort_values('Area',ascending=False).head()

Area  District  Latitude  Longitude
Pincode                                     
400001      5         5         5          5
400004      5         5         5          5
400028      5         5         5          5
400012      5         5         5          5
400003      4         4         4          4

In [84]:
dfd.groupby('Pincode').count().sort_values('Area',ascending=False).head()

Area  District  Latitude  Longitude
Pincode                                     
110001     15        15        15         15
110028     11        11        11         11
110015     11        11        11         11
110010     11        11        11         11
110095      8         8         8          8

In [85]:

#we identified Pincode 400003 and 110001 have the hihest places count in Mumbai and Delhi respectively
m_df = df[df['Pincode'] == '400003 '].reset_index(drop=True)
d_df = dfd[dfd['Pincode'] == '110001 '].reset_index(drop=True)



In [86]:
m_df.head()

Area  Pincode District   Latitude  Longitude
0  B P t colony  400003   Mumbai   19.101937  72.861599
1        Mandvi  400003   Mumbai   18.955056  72.834792
2        Masjid  400003   Mumbai   19.053051  72.832407
3    Null Bazar  400003   Mumbai   18.928665  72.832264

In [87]:
d_df.head()

Area  Pincode        District   Latitude  Longitude
0         Baroda House  110001   Central Delhi   28.615804  77.230020
1       Bengali Market  110001   Central Delhi   28.629465  77.232185
2      Connaught Place  110001   Central Delhi   28.631383  77.219792
3  Election Commission  110001   Central Delhi   28.448733  77.028976
4              Janpath  110001   Central Delhi   28.610086  77.218247

In [94]:
address = '400003, Mumbai'
geolocator = Nominatim(user_agent='my application')
location = geolocator.geocode(address, timeout=10)
latitude = location.latitude
longitude = location.longitude

# create map of Bukit Bintang using latitude and longitude values
map_400003 = folium.Map(location=[latitude, longitude], zoom_start=11)

# add markers to map
for lat, lng, label in zip(m_df['Latitude'], m_df['Longitude'], m_df['Area']):
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_400003)  
    
map_400003

In [95]:
address = '110001, Delhi'
geolocator = Nominatim(user_agent='my application')
location = geolocator.geocode(address, timeout=10)
latitude = location.latitude
longitude = location.longitude

# create map of Bukit Bintang using latitude and longitude values
map_110001 = folium.Map(location=[latitude, longitude], zoom_start=11)

# add markers to map
for lat, lng, label in zip(d_df['Latitude'], d_df['Longitude'], d_df['Area']):
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_110001)  
    
map_110001

Using Foursquare API to get venues at surounding area of both 400003 Mumbai and 110001 area.


In [101]:
import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

#Define Foursquare Credentials and Version
CLIENT_ID = '42RMX5YJWUHBI5XLF0LTY22OSXJZVCSMUFVKCTEQSPD1NX2G' # your Foursquare ID
CLIENT_SECRET = 'V5WJW5BYB3HWGT0BHAHO3NJXVJJ2K0U4VCVWYWQKGDEWGPI2' # your Foursquare Secret
VERSION = '20180604'

#explore the first neighborhood in our dataframe
#Get the neighborhood's latitude and longitude values.
neighborhood_latitude = d_df.loc[0, 'Latitude'] # neighborhood latitude value
neighborhood_longitude = d_df.loc[0, 'Longitude'] # neighborhood longitude value
neighborhood_name = d_df.loc[0, 'Area'] # neighborhood name

#get the top 100 venues that are in Bukit Bintang within a radius of 500 meters
LIMIT = 100 # limit of number of venues returned by Foursquare API
radius = 1000 # define radius
url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    neighborhood_latitude, 
    neighborhood_longitude, 
    radius, 
    LIMIT)

#Send the GET request and examine the resutls
results = requests.get(url).json()

#borrow the get_category_type function from the Foursquare lab.
# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

#clean the json and structure it into a pandas dataframe
venues = results['response']['groups'][0]['items']    
nearby_venues = json_normalize(venues) # flatten JSON

# filter columns
filtered_columns = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues =nearby_venues.loc[:, filtered_columns]

# filter the category for each row
nearby_venues['venue.categories'] = nearby_venues.apply(get_category_type, axis=1)

# clean columns
nearby_venues.columns = [col.split(".")[-1] for col in nearby_venues.columns]
print('{} venues were returned by Foursquare for 400003 Mumbai.'.format(nearby_venues.shape[0]))
nearby_venues.head()

25 venues were returned by Foursquare for 400003 Mumbai.


name           categories  \
0               India Gate | इंडिया गेट (India Gate)  Monument / Landmark   
1  Amar Jawan Jyoti | अमर जवान ज्योति (Amar Jawan...     Sculpture Garden   
2                              Andhra Bhavan Canteen    Indian Restaurant   
3                                  Gulati Restaurant    Indian Restaurant   
4  National Gallery Of Modern Art | राष्ट्रीय आधु...          Art Gallery   

         lat        lng  
0  28.612796  77.229207  
1  28.612980  77.228247  
2  28.617095  77.225721  
3  28.608010  77.229989  
4  28.609411  77.234585

In [102]:
import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

#Define Foursquare Credentials and Version
CLIENT_ID = '42RMX5YJWUHBI5XLF0LTY22OSXJZVCSMUFVKCTEQSPD1NX2G' # your Foursquare ID
CLIENT_SECRET = 'V5WJW5BYB3HWGT0BHAHO3NJXVJJ2K0U4VCVWYWQKGDEWGPI2' # your Foursquare Secret
VERSION = '20180604'

#explore the first neighborhood in our dataframe
#Get the neighborhood's latitude and longitude values.
neighborhood_latitude = d_df.loc[0, 'Latitude'] # neighborhood latitude value
neighborhood_longitude = d_df.loc[0, 'Longitude'] # neighborhood longitude value
neighborhood_name = d_df.loc[0, 'Area'] # neighborhood name

#get the top 100 venues that are in Bukit Bintang within a radius of 500 meters
LIMIT = 100 # limit of number of venues returned by Foursquare API
radius = 1000 # define radius
url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    neighborhood_latitude, 
    neighborhood_longitude, 
    radius, 
    LIMIT)

#Send the GET request and examine the resutls
results = requests.get(url).json()

#borrow the get_category_type function from the Foursquare lab.
# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

#clean the json and structure it into a pandas dataframe
venues = results['response']['groups'][0]['items']    
nearby_venues = json_normalize(venues) # flatten JSON

# filter columns
filtered_columns = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues =nearby_venues.loc[:, filtered_columns]

# filter the category for each row
nearby_venues['venue.categories'] = nearby_venues.apply(get_category_type, axis=1)

# clean columns
nearby_venues.columns = [col.split(".")[-1] for col in nearby_venues.columns]
print('{} venues were returned by Foursquare for 110001 Delhi.'.format(nearby_venues.shape[0]))
nearby_venues.head()

25 venues were returned by Foursquare for 110001 Delhi.


name           categories  \
0               India Gate | इंडिया गेट (India Gate)  Monument / Landmark   
1  Amar Jawan Jyoti | अमर जवान ज्योति (Amar Jawan...     Sculpture Garden   
2                              Andhra Bhavan Canteen    Indian Restaurant   
3                                  Gulati Restaurant    Indian Restaurant   
4  National Gallery Of Modern Art | राष्ट्रीय आधु...          Art Gallery   

         lat        lng  
0  28.612796  77.229207  
1  28.612980  77.228247  
2  28.617095  77.225721  
3  28.608010  77.229989  
4  28.609411  77.234585

In [103]:
#function to repeat the same process to all area
def getNearbyVenues(names, latitudes, longitudes, radius=1000):    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Area', 
                  'Area Latitude', 
                  'Area Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [104]:
m_venues = getNearbyVenues(names=m_df['Area'],
                                   latitudes=m_df['Latitude'],
                                   longitudes=m_df['Longitude']
                                  )

#check the size of the resulting dataframe
print(m_venues.shape)
m_venues.head()

B P t colony
Mandvi
Masjid
Null Bazar
(258, 7)


Area  Area Latitude  Area Longitude        Venue  Venue Latitude  \
0  B P t colony      19.101937       72.861599    Peshawari       19.103954   
1  B P t colony      19.101937       72.861599  ITC Maratha       19.104023   
2  B P t colony      19.101937       72.861599    Pan Asian       19.104424   
3  B P t colony      19.101937       72.861599    Hit & Run       19.107787   
4  B P t colony      19.101937       72.861599    Dum Pukth       19.104070   

   Venue Longitude      Venue Category  
0        72.869879   Indian Restaurant  
1        72.869638               Hotel  
2        72.869751    Asian Restaurant  
3        72.863333  Falafel Restaurant  
4        72.869822   Indian Restaurant

In [105]:
d_venues = getNearbyVenues(names=d_df['Area'],
                                   latitudes=d_df['Latitude'],
                                   longitudes=d_df['Longitude']
                                  )

#check the size of the resulting dataframe
print(d_venues.shape)
d_venues.head()

Baroda House
Bengali Market
Connaught Place
Election Commission
Janpath
Krishi Bhawan
North Avenue
Parliament House
Patiala House
Pragati Maidan
Rail Bhawan
Sansad Marg
Secretariat North
Shastri Bhawan
Supreme Court
(419, 7)


Area  Area Latitude  Area Longitude  \
0  Baroda House      28.615804        77.23002   
1  Baroda House      28.615804        77.23002   
2  Baroda House      28.615804        77.23002   
3  Baroda House      28.615804        77.23002   
4  Baroda House      28.615804        77.23002   

                                               Venue  Venue Latitude  \
0               India Gate | इंडिया गेट (India Gate)       28.612796   
1  Amar Jawan Jyoti | अमर जवान ज्योति (Amar Jawan...       28.612980   
2                              Andhra Bhavan Canteen       28.617095   
3                                  Gulati Restaurant       28.608010   
4  National Gallery Of Modern Art | राष्ट्रीय आधु...       28.609411   

   Venue Longitude       Venue Category  
0        77.229207  Monument / Landmark  
1        77.228247     Sculpture Garden  
2        77.225721    Indian Restaurant  
3        77.229989    Indian Restaurant  
4        77.234585          Art Gallery

In [106]:


#check how many venues were returned for each area
print('There are {} uniques categories in Mumbai.'.format(len(m_venues['Venue Category'].unique())))
m_venues.groupby('Area').count()



There are 81 uniques categories in Mumbai.


Area Latitude  Area Longitude  Venue  Venue Latitude  \
Area                                                                 
B P t colony             16              16     16              16   
Mandvi                   42              42     42              42   
Masjid                  100             100    100             100   
Null Bazar              100             100    100             100   

              Venue Longitude  Venue Category  
Area                                           
B P t colony               16              16  
Mandvi                     42              42  
Masjid                    100             100  
Null Bazar                100             100

In [107]:
print('There are {} uniques categories in Delhi.'.format(len(d_venues['Venue Category'].unique())))
d_venues.groupby('Area').count()

There are 77 uniques categories in Delhi.


Area Latitude  Area Longitude  Venue  Venue Latitude  \
Area                                                                        
Baroda House                    25              25     25              25   
Bengali Market                  26              26     26              26   
Connaught Place                 78              78     78              78   
Election Commission              4               4      4               4   
Janpath                         25              25     25              25   
Krishi Bhawan                   24              24     24              24   
North Avenue                     8               8      8               8   
Parliament House                13              13     13              13   
Patiala House                   25              25     25              25   
Pragati Maidan                  17              17     17              17   
Rail Bhawan                     28              28     28              28   
Sansad Marg                     94              94     94              94   
Secretariat North                7               7      7               7   
Shastri Bhawan                  23              23     23              23   
Supreme Court                   22              22     22              22   

                     Venue Longitude  Venue Category  
Area                                                  
Baroda House                      25              25  
Bengali Market                    26              26  
Connaught Place                   78              78  
Election Commission                4               4  
Janpath                           25              25  
Krishi Bhawan                     24              24  
North Avenue                       8               8  
Parliament House                  13              13  
Patiala House                     25              25  
Pragati Maidan                    17              17  
Rail Bhawan                       28              28  
Sansad Marg                       94              94  
Secretariat North                  7               7  
Shastri Bhawan                    23              23  
Supreme Court                     22              22

Analysing


In [108]:


# one hot encoding
m_onehot = pd.get_dummies(m_venues[['Venue Category']], prefix="", prefix_sep="")
m_onehot.head()



Airport  American Restaurant  Antique Shop  Arcade  Art Gallery  \
0        0                    0             0       0            0   
1        0                    0             0       0            0   
2        0                    0             0       0            0   
3        0                    0             0       0            0   
4        0                    0             0       0            0   

   Asian Restaurant  BBQ Joint  Bakery  Bar  Bookstore  ...  Smoke Shop  \
0                 0          0       0    0          0  ...           0   
1                 0          0       0    0          0  ...           0   
2                 1          0       0    0          0  ...           0   
3                 0          0       0    0          0  ...           0   
4                 0          0       0    0          0  ...           0   

   Snack Place  Stadium  Steakhouse  Tea Room  Thai Restaurant  Theater  \
0            0        0           0         0                0        0   
1            0        0           0         0                0        0   
2            0        0           0         0                0        0   
3            0        0           0         0                0        0   
4            0        0           0         0                0        0   

   Train Station  Vegetarian / Vegan Restaurant  Women's Store  
0              0                              0              0  
1              0                              0              0  
2              0                              0              0  
3              0                              0              0  
4              0                              0              0  

[5 rows x 81 columns]

In [109]:


# add neighborhood column back to dataframe
m_onehot['Area'] = m_venues['Area'] 
m_onehot.head()



Airport  American Restaurant  Antique Shop  Arcade  Art Gallery  \
0        0                    0             0       0            0   
1        0                    0             0       0            0   
2        0                    0             0       0            0   
3        0                    0             0       0            0   
4        0                    0             0       0            0   

   Asian Restaurant  BBQ Joint  Bakery  Bar  Bookstore  ...  Snack Place  \
0                 0          0       0    0          0  ...            0   
1                 0          0       0    0          0  ...            0   
2                 1          0       0    0          0  ...            0   
3                 0          0       0    0          0  ...            0   
4                 0          0       0    0          0  ...            0   

   Stadium  Steakhouse  Tea Room  Thai Restaurant  Theater  Train Station  \
0        0           0         0                0        0              0   
1        0           0         0                0        0              0   
2        0           0         0                0        0              0   
3        0           0         0                0        0              0   
4        0           0         0                0        0              0   

   Vegetarian / Vegan Restaurant  Women's Store          Area  
0                              0              0  B P t colony  
1                              0              0  B P t colony  
2                              0              0  B P t colony  
3                              0              0  B P t colony  
4                              0              0  B P t colony  

[5 rows x 82 columns]

In [110]:


# move neighborhood column to the first column
fixed_columns = [m_onehot.columns[-1]] + list(m_onehot.columns[:-1])
m_onehot = m_onehot[fixed_columns]

m_onehot.head()



Area  Airport  American Restaurant  Antique Shop  Arcade  \
0  B P t colony        0                    0             0       0   
1  B P t colony        0                    0             0       0   
2  B P t colony        0                    0             0       0   
3  B P t colony        0                    0             0       0   
4  B P t colony        0                    0             0       0   

   Art Gallery  Asian Restaurant  BBQ Joint  Bakery  Bar  ...  Smoke Shop  \
0            0                 0          0       0    0  ...           0   
1            0                 0          0       0    0  ...           0   
2            0                 1          0       0    0  ...           0   
3            0                 0          0       0    0  ...           0   
4            0                 0          0       0    0  ...           0   

   Snack Place  Stadium  Steakhouse  Tea Room  Thai Restaurant  Theater  \
0            0        0           0         0                0        0   
1            0        0           0         0                0        0   
2            0        0           0         0                0        0   
3            0        0           0         0                0        0   
4            0        0           0         0                0        0   

   Train Station  Vegetarian / Vegan Restaurant  Women's Store  
0              0                              0              0  
1              0                              0              0  
2              0                              0              0  
3              0                              0              0  
4              0                              0              0  

[5 rows x 82 columns]

In [111]:
#examine the new dataframe size after one hot encoding
print('{} rows were returned after one hot encoding.'.format(m_onehot.shape[0]))


#group rows by neighborhood and by taking the mean of the frequency of occurrence of each category
m_grouped = m_onehot.groupby('Area').mean().reset_index()
m_grouped.head()



258 rows were returned after one hot encoding.


Area  Airport  American Restaurant  Antique Shop   Arcade  \
0  B P t colony   0.0625              0.00000       0.00000  0.00000   
1        Mandvi   0.0000              0.02381       0.02381  0.02381   
2        Masjid   0.0000              0.00000       0.00000  0.01000   
3    Null Bazar   0.0000              0.00000       0.00000  0.00000   

   Art Gallery  Asian Restaurant  BBQ Joint  Bakery     Bar  ...  Smoke Shop  \
0         0.00            0.0625    0.00000    0.00  0.0625  ...        0.00   
1         0.00            0.0000    0.02381    0.00  0.0000  ...        0.00   
2         0.00            0.0300    0.01000    0.04  0.0600  ...        0.01   
3         0.01            0.0200    0.00000    0.04  0.0400  ...        0.00   

   Snack Place  Stadium  Steakhouse  Tea Room  Thai Restaurant  Theater  \
0         0.00     0.00        0.00      0.00             0.00     0.00   
1         0.00     0.00        0.00      0.00             0.00     0.00   
2         0.03     0.00        0.01      0.02             0.01     0.01   
3         0.00     0.01        0.00      0.00             0.00     0.00   

   Train Station  Vegetarian / Vegan Restaurant  Women's Store  
0           0.00                           0.00           0.00  
1           0.00                           0.00           0.00  
2           0.01                           0.01           0.01  
3           0.00                           0.01           0.00  

[4 rows x 82 columns]

In [112]:
print('{} rows were returned after grouping.'.format(m_grouped.shape[0]))

4 rows were returned after grouping.


In [113]:
num_top_venues = 5

for hood in m_grouped['Area']:
    print("----"+hood+"----")
    temp = m_grouped[m_grouped['Area'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')


----B P t colony----
                  venue  freq
0     Indian Restaurant  0.31
1                 Hotel  0.19
2               Airport  0.06
3                   Bar  0.06
4  Fast Food Restaurant  0.06


----Mandvi----
               venue  freq
0  Indian Restaurant  0.31
1    Harbor / Marina  0.07
2     Ice Cream Shop  0.07
3       Dessert Shop  0.07
4         Restaurant  0.05


----Masjid----
               venue  freq
0               Café  0.11
1  Indian Restaurant  0.09
2                Bar  0.06
3        Coffee Shop  0.04
4             Bakery  0.04


----Null Bazar----
                venue  freq
0   Indian Restaurant  0.13
1                Café  0.08
2  Chinese Restaurant  0.05
3              Bakery  0.04
4                 Bar  0.04




In [114]:
#put into a pandas dataframe

#write a function to sort the venues in descending order
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

#create the new dataframe and display the top 10 venues for each neighborhood
num_top_venues = 8

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Area']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
areas_venues_sorted = pd.DataFrame(columns=columns)
areas_venues_sorted['Area'] = m_grouped['Area']

for ind in np.arange(m_grouped.shape[0]):
    areas_venues_sorted.iloc[ind, 1:] = return_most_common_venues(m_grouped.iloc[ind, :], num_top_venues)

areas_venues_sorted.head()

Area 1st Most Common Venue 2nd Most Common Venue  \
0  B P t colony     Indian Restaurant                 Hotel   
1        Mandvi     Indian Restaurant        Ice Cream Shop   
2        Masjid                  Café     Indian Restaurant   
3    Null Bazar     Indian Restaurant                  Café   

  3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
0               Airport                   Bar                  Café   
1       Harbor / Marina          Dessert Shop     Convenience Store   
2                   Bar                Bakery           Coffee Shop   
3    Chinese Restaurant                Bakery                   Bar   

  6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  
0    Falafel Restaurant  Fast Food Restaurant    Seafood Restaurant  
1            Restaurant                Market             BBQ Joint  
2  Gym / Fitness Center      Asian Restaurant           Snack Place  
3   Japanese Restaurant                 Hotel  Fast Food Restaurant

In [115]:
from sklearn.cluster import KMeans

# set number of clusters
kclusters = 3

m_grouped_clustering = m_grouped.drop('Area', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(m_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10] 

#create a new dataframe that includes the cluster as well as the top 10 venues for each neighborhood.
m_merged = m_df

# add clustering labels
m_merged['Cluster Labels'] = kmeans.labels_


m_merged



Area  Pincode District   Latitude  Longitude  Cluster Labels
0  B P t colony  400003   Mumbai   19.101937  72.861599               0
1        Mandvi  400003   Mumbai   18.955056  72.834792               2
2        Masjid  400003   Mumbai   19.053051  72.832407               1
3    Null Bazar  400003   Mumbai   18.928665  72.832264               1

In [116]:
m_merged = m_merged.join(areas_venues_sorted.set_index('Area'), on='Area')

m_merged.head()

Area  Pincode District   Latitude  Longitude  Cluster Labels  \
0  B P t colony  400003   Mumbai   19.101937  72.861599               0   
1        Mandvi  400003   Mumbai   18.955056  72.834792               2   
2        Masjid  400003   Mumbai   19.053051  72.832407               1   
3    Null Bazar  400003   Mumbai   18.928665  72.832264               1   

  1st Most Common Venue 2nd Most Common Venue 3rd Most Common Venue  \
0     Indian Restaurant                 Hotel               Airport   
1     Indian Restaurant        Ice Cream Shop       Harbor / Marina   
2                  Café     Indian Restaurant                   Bar   
3     Indian Restaurant                  Café    Chinese Restaurant   

  4th Most Common Venue 5th Most Common Venue 6th Most Common Venue  \
0                   Bar                  Café    Falafel Restaurant   
1          Dessert Shop     Convenience Store            Restaurant   
2                Bakery           Coffee Shop  Gym / Fitness Center   
3                Bakery                   Bar   Japanese Restaurant   

  7th Most Common Venue 8th Most Common Venue  
0  Fast Food Restaurant    Seafood Restaurant  
1                Market             BBQ Joint  
2      Asian Restaurant           Snack Place  
3                 Hotel  Fast Food Restaurant

In [122]:


# one hot encoding
d_onehot = pd.get_dummies(d_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
d_onehot['Area'] = d_venues['Area'] 

# move neighborhood column to the first column
fixed_columns = [d_onehot.columns[-1]] + list(d_onehot.columns[:-1])
d_onehot = d_onehot[fixed_columns]

#examine the new dataframe size after one hot encoding
print('{} rows were returned after one hot encoding.'.format(d_onehot.shape[0]))

#group rows by neighborhood and by taking the mean of the frequency of occurrence of each category
d_grouped = d_onehot.groupby('Area').mean().reset_index()

#examine the new dataframe size after one hot encoding
print('{} rows were returned after grouping.'.format(d_grouped.shape[0]))



419 rows were returned after one hot encoding.
15 rows were returned after grouping.


In [123]:
#print each neighborhood along with the top 5 most common venues
num_top_venues = 5

for hood in d_grouped['Area']:
    print("----"+hood+"----")
    temp = d_grouped[d_grouped['Area'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))

----Baroda House----
                venue  freq
0   Indian Restaurant  0.20
1                Pool  0.08
2          Smoke Shop  0.08
3  Chinese Restaurant  0.08
4           Cafeteria  0.04
----Bengali Market----
               venue  freq
0            Theater  0.12
1               Café  0.12
2        Art Gallery  0.08
3  Indian Restaurant  0.08
4             Bakery  0.08
----Connaught Place----
                venue  freq
0   Indian Restaurant  0.13
1                Café  0.09
2         Coffee Shop  0.05
3                 Bar  0.05
4  Chinese Restaurant  0.05
----Election Commission----
                        venue  freq
0                Home Service  0.25
1  Tourist Information Center  0.25
2                 Golf Course  0.25
3                       Hotel  0.25
4                      Museum  0.00
----Janpath----
                venue  freq
0   Indian Restaurant  0.16
1           Hotel Bar  0.12
2  Chinese Restaurant  0.08
3      History Museum  0.08
4               Hotel  0.08
----Kr

In [124]:
#create the new dataframe and display the top 10 venues for each neighborhood
num_top_venues = 8

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Area']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
areas_venues_sorted = pd.DataFrame(columns=columns)
areas_venues_sorted['Area'] = d_grouped['Area']

for ind in np.arange(d_grouped.shape[0]):
    areas_venues_sorted.iloc[ind, 1:] = return_most_common_venues(d_grouped.iloc[ind, :], num_top_venues)

areas_venues_sorted.head()



Area 1st Most Common Venue       2nd Most Common Venue  \
0         Baroda House     Indian Restaurant                  Smoke Shop   
1       Bengali Market               Theater                        Café   
2      Connaught Place     Indian Restaurant                        Café   
3  Election Commission           Golf Course  Tourist Information Center   
4              Janpath     Indian Restaurant                   Hotel Bar   

  3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
0                  Pool    Chinese Restaurant      Sculpture Garden   
1           Art Gallery                 Hotel     Indian Restaurant   
2           Coffee Shop                   Bar    Chinese Restaurant   
3                 Hotel          Home Service              Wine Bar   
4                 Hotel    Chinese Restaurant        History Museum   

  6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  
0                  Park          Concert Hall     Food & Drink Shop  
1                Bakery                Arcade          Burger Joint  
2                 Hotel  Fast Food Restaurant                Lounge  
3  Fast Food Restaurant           Flea Market     Food & Drink Shop  
4           Snack Place             Rest Area            Restaurant

In [125]:
# set number of clusters
kclusters = 3

d_grouped_clustering = d_grouped.drop('Area', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(d_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10] 

#create a new dataframe that includes the cluster as well as the top 10 venues for each neighborhood.
d_merged = d_df

# add clustering labels
d_merged['Cluster Labels'] = kmeans.labels_

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
d_merged = d_merged.join(areas_venues_sorted.set_index('Area'), on='Area')

d_merged.head() # check the last columns!

Area  Pincode        District   Latitude  Longitude  \
0         Baroda House  110001   Central Delhi   28.615804  77.230020   
1       Bengali Market  110001   Central Delhi   28.629465  77.232185   
2      Connaught Place  110001   Central Delhi   28.631383  77.219792   
3  Election Commission  110001   Central Delhi   28.448733  77.028976   
4              Janpath  110001   Central Delhi   28.610086  77.218247   

   Cluster Labels 1st Most Common Venue       2nd Most Common Venue  \
0               1     Indian Restaurant                  Smoke Shop   
1               0               Theater                        Café   
2               1     Indian Restaurant                        Café   
3               2           Golf Course  Tourist Information Center   
4               1     Indian Restaurant                   Hotel Bar   

  3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
0                  Pool    Chinese Restaurant      Sculpture Garden   
1           Art Gallery                 Hotel     Indian Restaurant   
2           Coffee Shop                   Bar    Chinese Restaurant   
3                 Hotel          Home Service              Wine Bar   
4                 Hotel    Chinese Restaurant        History Museum   

  6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  
0                  Park          Concert Hall     Food & Drink Shop  
1                Bakery                Arcade          Burger Joint  
2                 Hotel  Fast Food Restaurant                Lounge  
3  Fast Food Restaurant           Flea Market     Food & Drink Shop  
4           Snack Place             Rest Area            Restaurant

Result


In [130]:


#Cluster 1 for Mumbai
m_merged.loc[m_merged['Cluster Labels'] == 0, m_merged.columns[[2] + list(range(5, m_merged.shape[1]))]]



District  Cluster Labels 1st Most Common Venue 2nd Most Common Venue  \
1  Mumbai                2     Indian Restaurant        Ice Cream Shop   

  3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
1       Harbor / Marina          Dessert Shop     Convenience Store   

  6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  
1            Restaurant                Market             BBQ Joint

In [131]:
#Cluster 2 for Mumbai
m_merged.loc[m_merged['Cluster Labels'] == 1, m_merged.columns[[2] + list(range(5, m_merged.shape[1]))]]


District  Cluster Labels 1st Most Common Venue 2nd Most Common Venue  \
2  Mumbai                1                  Café     Indian Restaurant   
3  Mumbai                1     Indian Restaurant                  Café   

  3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
2                   Bar                Bakery           Coffee Shop   
3    Chinese Restaurant                Bakery                   Bar   

  6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  
2  Gym / Fitness Center      Asian Restaurant           Snack Place  
3   Japanese Restaurant                 Hotel  Fast Food Restaurant

In [132]:
#Cluster 3 for Mumbai
m_merged.loc[m_merged['Cluster Labels'] == 2, m_merged.columns[[2] + list(range(5, m_merged.shape[1]))]]


District  Cluster Labels 1st Most Common Venue 2nd Most Common Venue  \
1  Mumbai                2     Indian Restaurant        Ice Cream Shop   

  3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
1       Harbor / Marina          Dessert Shop     Convenience Store   

  6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  
1            Restaurant                Market             BBQ Joint

In [133]:


#Cluster 1 for Delhi
d_merged.loc[d_merged['Cluster Labels'] == 0, d_merged.columns[[2] + list(range(5, d_merged.shape[1]))]]



District  Cluster Labels 1st Most Common Venue  \
1   Central Delhi                0               Theater   
8   Central Delhi                0           Art Gallery   
9   Central Delhi                0           Art Gallery   
14  Central Delhi                0           Art Gallery   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
1                   Café           Art Gallery                 Hotel   
8      Indian Restaurant                  Pool      Sculpture Garden   
9                Theater                  Pool           Coffee Shop   
14               Theater                  Café                Arcade   

   5th Most Common Venue   6th Most Common Venue   7th Most Common Venue  \
1      Indian Restaurant                  Bakery                  Arcade   
8             Smoke Shop                    Park  Furniture / Home Store   
9     Chinese Restaurant      Light Rail Station  Furniture / Home Store   
14                 Hotel  Furniture / Home Store             Flea Market   

    8th Most Common Venue  
1            Burger Joint  
8            Concert Hall  
9             Flea Market  
14  Performing Arts Venue

In [134]:
#Cluster 2 for Delhi
d_merged.loc[d_merged['Cluster Labels'] == 1, d_merged.columns[[2] + list(range(5, d_merged.shape[1]))]]

District  Cluster Labels 1st Most Common Venue  \
0   Central Delhi                1     Indian Restaurant   
2   Central Delhi                1     Indian Restaurant   
4   Central Delhi                1     Indian Restaurant   
5   Central Delhi                1                 Hotel   
6   Central Delhi                1     Indian Restaurant   
7   Central Delhi                1     Indian Restaurant   
10  Central Delhi                1                 Hotel   
11  Central Delhi                1     Indian Restaurant   
12  Central Delhi                1     Indian Restaurant   
13  Central Delhi                1     Indian Restaurant   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
0             Smoke Shop                  Pool    Chinese Restaurant   
2                   Café           Coffee Shop                   Bar   
4              Hotel Bar                 Hotel    Chinese Restaurant   
5      Indian Restaurant            Restaurant        History Museum   
6       Asian Restaurant               Theater               Stadium   
7                 Museum             Hotel Bar                Hostel   
10     Indian Restaurant            Restaurant        History Museum   
11                 Hotel                  Café                   Bar   
12           Music Venue              Tea Room                Museum   
13                 Hotel        History Museum            Restaurant   

   5th Most Common Venue 6th Most Common Venue 7th Most Common Venue  \
0       Sculpture Garden                  Park          Concert Hall   
2     Chinese Restaurant                 Hotel  Fast Food Restaurant   
4         History Museum           Snack Place             Rest Area   
5     Light Rail Station                Lounge         Historic Site   
6       Spiritual Center                Garden            Smoke Shop   
7      Food & Drink Shop    Light Rail Station        History Museum   
10              Wine Bar                   Bar    Chinese Restaurant   
11    Chinese Restaurant           Coffee Shop    Italian Restaurant   
12      Spiritual Center                Garden   Government Building   
13    Chinese Restaurant    Light Rail Station                Lounge   

   8th Most Common Venue  
0      Food & Drink Shop  
2                 Lounge  
4             Restaurant  
5    Government Building  
6          Historic Site  
7       Spiritual Center  
10        Clothing Store  
11                Lounge  
12           Golf Course  
13         Historic Site

In [135]:


#Cluster 3 for Delhi
d_merged.loc[d_merged['Cluster Labels'] == 2, d_merged.columns[[2] + list(range(5, d_merged.shape[1]))]]



District  Cluster Labels 1st Most Common Venue  \
3  Central Delhi                2           Golf Course   

        2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
3  Tourist Information Center                 Hotel          Home Service   

  5th Most Common Venue 6th Most Common Venue 7th Most Common Venue  \
3              Wine Bar  Fast Food Restaurant           Flea Market   

  8th Most Common Venue  
3     Food & Drink Shop


Discussion

Based on cluster for each cities above, we believe that classification for each cluster can be done better with calculation of venues categories (most common) in each cities. Refering to each clsuter, we can't deterimine clearly what represent in each cluster by using Foursquare - Most Common Venue data.

However, for the sae of this project we assumed each cluster as follow:

-- Cluster 1: Mumbai: Tourism -- Cluster 2: Mumbai: Residental -- Cluster 3: Mumbai: Mix -- ster 1: Delhi: Residental -- ster 2: Delhi: Tourism -- ster 3: Delhi: Sport

What is lacking at this point is a systematic, quantitative way to identify and distinguish different district and to describe the correlation most common venues as recorded in Foursquare. The reality is however more complex: similar cities might have or might not have similar common venues. A further step in this classification would be to find a method to extract these common venues and integrate the spatial correlations between different of areas or district.

We believe that the classification we propose is an encouraging step towards a quantitative and systematic comparison of the different cities. Further studies are indeed needed in order to relate the data acquired, then observe it to more meaningful and objective results.


Conclusion

Using Foursquare API, we can captured data of common places all around the world. Using it, we refer back to our main objectives, which is to determine;

the similarity or dissimilarirty of both cities classification of area located inside the city whether it is residential, tourism places, or others

In conclusion, both cities Mumbai and Delhi are the center of attraction among Indians. However, to declare both cities are similar or dissimilar base on common venues visited is quite difficult. Both cities is similar in some venues also dissimilar in certain venues. And for classitification based on common venues, again we must have more systematic or quantitative way to identify and declare this. Comparison can be made, but no such method or quantitative data to determine this. We hope in the future, a method to determine it can be establish and explore for references.

Thank you.
